name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Restore dependencies
        run: dotnet restore && dotnet tool restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info
      - name: Coverage Report
        run: dotnet tool run reportgenerator -reports:"**/lcov.info" -reporttypes:"Html" -targetdir:./coverage-report/unit-coverage

  deployment:
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: Main
    env:
      BASE_VERSION: 0.0.
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Restore dependencies
        run: dotnet restore && dotnet tool restore
      - name: Pack
        run: dotnet pack --include-symbols --configuration release -p:PackageVersion=$BASE_VERSION$GITHUB_RUN_NUMBER -p:SymbolPackageFormat=snupkg
      - name: Publish nuget
        run: dotnet nuget push Munix.Miniflux/bin/Release/Munix.Miniflux.$BASE_VERSION$GITHUB_RUN_NUMBER.nupkg -k ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json